#define NDF_LIBRARY_ID 15061996
#define RIGHT_CLIENT_MANAGEMENT 0
#define RIGHT_OWNER 49
#define NDF_MAIN_PAGE_ID 1
#define NDF_ADDWORKER_PAGE_ID 2
#define NDF_VIEWACCOUNT_PAGE_ID 3
#define NDF_SELECTUSER_PAGE_ID 4
#define NDF_VALID_PAGE_ID 5
